### PR TITLE
Removed LOWER function from the query

### PR DESCRIPTION
**Pull request by jamshaid120**
I compiled the application and started the app as per the given instruction with the provided database queries. If I use the LOWER function, it returns null as for the queries as the insert statements keep the data in mixed cases. Either the data should have been updated there or the code here should have been updated. I preferred updating the code as the user may enter the ruleName and other data in the database using any case and the LOWER function will always return null in that case as it was in mine. 
Please review and update the change. Thanks

### CODE REVIEW

**Review by DeanLee77 — COMMENTED** [review]
this application itself is designed to have a role of dashboard kind of stuff as well so all rule name was handled as lower cases. However, if you also need to do some stuff via database directly then I agree with what you commented.

I have merged your changes, and thanks for your effort and commit.

**Comment by jamshaid120** [comment]
Thanks for the approval. :)

**Comment by jamshaid120** [comment]
Thanks for the approval. :)

**Comment by DeanLee77** [comment]
By the way, May I ask how you found this app, and any comments on the app?

**Comment by jamshaid120** [comment]
I was given a task to install this app on a server and test it. Before installing on the server, I tested it on my own linux machine and found those errors. I am still testing the application. For the shorter review, it doesn't point to any page for **Learn Nadia** and **Nadia Demo** in the GUI part.
If coming to rules writing and other stuff, I didn't write any rules yet. It's kinda good to see what I learned in my previous semester while studying artificial intelligence in real implemented form and running as a professional project

**Comment by DeanLee77** [comment]
So sounds like you have a task within your Uni. course. It is interesting for me that your lecturer/professor found this app, and give students a task of playing with it. What is the actual task, may I ask? And If you have any questions about the engine, please let me know.

There are no pages for 'Learn Nadia' and 'Nadia Demo'. For your information, there is a kind of Demo video that can be found as a link form in the README of NadiaRS repository. If you have any help or difficulties with writing rules then I can send you a document for that.

**Comment by jamshaid120** [comment]
It's not a university assignment. It in fact is a paid task to me by a person. He asked me to install and run this app on his server. Maybe they want to have something done by this. 
I watched that video and found this project interesting. That's why I am working over it. I would like to test this app further as well. 
Please consider sharing the rules writing page with me as well. I'll try to understand the strategy you are following in your spring application. 
I tested a sample but couldn't understand the way of writing rules. I've been working for a few months and didn't find the time after that. I'm happy to have this application in my knowledge. I can enhance my skills with this one. :)

**Comment by DeanLee77** [comment]
Please send me your email address to  'nexst.rndlabs@gmail.com' then I can forward you a document.

**Comment by jamshaid120** [comment]
Just sent you the email. Thanks for your time! :)

**Pull request merged**
